### ISSUE TITLE
'Share' button blocks some interactions

### ISSUE THREAD

**Issue by abusedmedia** [todotoit/cryptoloji#83] opened 2016-02-26 16:33 UTC
It happens on Desktop version, check the attached 
![screenshot 2016-02-26 17 32 07](https://cloud.githubusercontent.com/assets/870788/13358329/15a88080-dcaf-11e5-8844-83ed5889fed4.png)
screenshot

**Comment by endorama** [comment] 2016-02-26 17:27
Duplicate of #75, adding browser information to #75 and closing.

**Closed by endorama** 2016-02-26 17:27 UTC
Labels: bug
