### ISSUE TITLE
Blinking cursor in input field

### ISSUE THREAD

**Issue by michellenebiolo** [todotoit/cryptoloji#105] opened 2016-03-04 12:30 UTC
![00c57e2e-e156-11e5-9f29-525d69c9c91f](https://cloud.githubusercontent.com/assets/9842076/13527127/28ed10bc-e20d-11e5-9258-743b7268a456.png)

**Comment by marcoaimo** [comment] 2016-03-07 12:35
I closed this issue in https://github.com/todotoit/cryptoloji/commit/8f03c343a0d789a92ac14079bb483c79926c9eda but this behavior is a bit buggish in landscape device like ipad, because focus event can't be trigger automatically without a user initiated event.

**Comment by abusedmedia** [comment] 2016-03-07 14:06
On mobile device, giving a focus on textfield should trigger also the keyboard, which is not the intended behaviour.
IMHO the blink cursor should be activate only on desktop devices.

**Closed** 2016-03-07 15:01 UTC
Labels: enhancement
